version: '3'
services:
  torimo-es01:
    build: ./elasticsearch
    container_name: torimo-es01
    environment:
      - node.name=torimo-es01
      - discovery.seed_hosts=torimo-es02
      - cluster.initial_master_nodes=torimo-es01,torimo-es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - torimo-esnet
  torimo-es02:
    build: ./elasticsearch
    container_name: torimo-es02
    environment:
      - node.name=torimo-es02
      - discovery.seed_hosts=torimo-es01
      - cluster.initial_master_nodes=torimo-es01,torimo-es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - torimo-esnet
  torimo-kibana:
    build: ./kibana
    container_name: torimo-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://torimo-es01:9200
    ports:
      - 5601:5601
    networks:
      - torimo-esnet

  torimo-search-api:
    image: torimo-search/jar:latest
    container_name: torimo-search-api
    ports:
      - 8080:8080
    depends_on:
      - torimo-es01

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  torimo-esnet:
